config/routes.rb
Weather::Application.routes.draw do

  resources :subscriptions, :temperatures, :points, :logs, :blogs, :runs

  resources :locations

  root to: 'locations#show', id: '97202'

  get 'locations', to: 'locations#index'

end

app/models/temperature.rb
class Temperature < ActiveRecord::Base

	def self.scrape_map(page)
		gfs = Nokogiri::HTML(open(page))
		gfs.css("map")[0].css("area")
	end

	def self.collect
		page = 'http://www.wrh.noaa.gov/mesowest/mwmap.php?map=portland'
		map = scrape_map(page)
		map.each do |area|
			puts area["onmouseover"]
		end
	end

end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController

  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  def index
    @temperatures = Temperature.all
  end

  def show
  end

  def new
    @temperature = Temperature.new
  end

  def edit
  end

  def create
    @temperature = Temperature.new(temperature_params)
    respond_to do |format|
      if @temperature.save
        format.html { redirect_to @temperature, notice: 'Temperature was successfully created.' }
        format.json { render action: 'show', status: :created, location: @temperature }
      else
        format.html { render action: 'new' }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to @temperature, notice: 'Temperature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url }
      format.json { head :no_content }
    end
  end

  private

  def set_temperature
    @temperature = Temperature.find(params[:id])
  end

  def temperature_params
    params.require(:temperature).permit(:temperature, :latitude, :longitude, :location, :name, :elevation, :precipitation, :altimiter)
  end

end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
end

app/views/temperatures/index.html.erb
<h1>Listing temperatures</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Location</th>
      <th>Name</th>
      <th>Elevation</th>
      <th>Precipitation</th>
      <th>Altimiter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @temperatures.each do |temperature| %>
      <tr>
        <td><%= temperature.temperature %></td>
        <td><%= temperature.latitude %></td>
        <td><%= temperature.longitude %></td>
        <td><%= temperature.location %></td>
        <td><%= temperature.name %></td>
        <td><%= temperature.elevation %></td>
        <td><%= temperature.precipitation %></td>
        <td><%= temperature.altimiter %></td>
        <td><%= link_to 'Show', temperature %></td>
        <td><%= link_to 'Edit', edit_temperature_path(temperature) %></td>
        <td><%= link_to 'Destroy', temperature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperature', new_temperature_path %>

app/views/temperatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @temperature.temperature %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @temperature.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @temperature.longitude %>
</p>

<p>
  <strong>Location:</strong>
  <%= @temperature.location %>
</p>

<p>
  <strong>Name:</strong>
  <%= @temperature.name %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @temperature.elevation %>
</p>

<p>
  <strong>Precipitation:</strong>
  <%= @temperature.precipitation %>
</p>

<p>
  <strong>Altimiter:</strong>
  <%= @temperature.altimiter %>
</p>

<%= link_to 'Edit', edit_temperature_path(@temperature) %> |
<%= link_to 'Back', temperatures_path %>