config/routes.rb
Weather::Application.routes.draw do

  resources :subscriptions, :temperatures, :points, :logs, :blogs, :runs

  resources :locations

  root to: 'locations#show', id: '97202'

  get 'locations', to: 'locations#index'

end

app/models/run.rb
class Run < ActiveRecord::Base
  include MeteostarModule
  include NWSModule

  has_many :points
  belongs_to :location

  def self.store_run(run,location)
    r = new
    r.location_id = location
    r.run_time = run
    r.save
    r.id
  end

  def self.most_recent(location)
    Run.where(location: location).order('run').last
  end

  def self.search_runs(run,page,location)
    existing_run = Run.find_by run_time: run, location_id: location.id
    if !existing_run
      Log.create_log('creating run',run,location.code,'','','')
      run_id = Run.store_run(run,location.id)
    end
    if run_id
      run_id
    else
      nil
    end
  end

  def self.strip_crap(string)
    string.gsub("\n","").strip.tr('^A-Za-z0-9.','')
  end

  def self.parse_time(text)
    m = text[3..4]
    d = text[5..6]
    h = text[7..8]
    t = Time.new('2014',m,d,h)
  end
  
  def self.run_this_before_restarting_the_server
    # but after migrate
    Run.all.each do |run|
      if !run.location_id
        run.location_id = Location.find_by_code(run.location).id
        run.save
      end
      if !run.run_time
        run.run_time = Time.parse(run.run)
        run.save
      end
    end
  end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController

  before_action :set_run, only: [:show, :edit, :update, :destroy]

  def index
    @runs = Run.all
  end

  def show
  end

  def new
    @run = Run.new
  end

  def edit
  end

  def create
    @run = Run.new(run_params)
    respond_to do |format|
      if @run.save
        format.html { redirect_to @run, notice: 'Run was successfully created.' }
        format.json { render action: 'show', status: :created, location: @run }
      else
        format.html { render action: 'new' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @run.update(run_params)
        format.html { redirect_to @run, notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @run.destroy
    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  private

  def set_run
    @run = Run.find(params[:id])
  end

  def run_params
    params.require(:run).permit(:run, :location, :model)
  end

end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/edit.html.erb
<h1>Editing run</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', runs_path %>

app/views/runs/index.html.erb
<h1 class="text-center">Runs</h1>
<table class="table">
  <thead>
    <tr>
      <th>Run</th>
      <th>Location</th>
      <th>Model</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @runs.each do |run| %>
      <tr>
        <td><%= run.run %></td>
        <td><%= run.location %></td>
        <td><%= run.model %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/runs/new.html.erb
<h1>New run</h1>

<%= render 'form' %>

<%= link_to 'Back', runs_path %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Run:</strong>
  <%= @run.run %>
</p>

<p>
  <strong>Location:</strong>
  <%= @run.location %>
</p>

<p>
  <strong>Model:</strong>
  <%= @run.model %>
</p>

<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', runs_path %>