config/routes.rb
Weather::Application.routes.draw do

  resources :subscriptions, :temperatures, :points, :logs, :blogs, :runs

  resources :locations

  root to: 'locations#show', id: '97202'

  get 'locations', to: 'locations#index'

end

app/models/log.rb
class Log < ActiveRecord::Base

  scope :future, lambda { |location| where( 'created_at > ? and location = locaiton', DateTime.yesterday.end_of_day , location ) }

  def self.create_log(action,run,location,time,email,note)
    log = new
    log.location = location
    log.action = action
    log.email = email
    log.note = note
    log.time = time
    log.run = run
    log.save
    log
  end
  
  def update_email_log(note)
    self.note = note
    self.save
    self
  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  before_action :set_log, only: [:show, :edit, :update, :destroy]

  def index
    @logs = Log.all.order(:created_at).reverse
  end

  def show
  end

  def new
    @log = Log.new
  end

  def edit
  end

  def create
    @log = Log.new(log_params)
    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @log }
      else
        format.html { render action: 'new' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end

  private

  def set_log
    @log = Log.find(params[:id])
  end

  def log_params
    params.require(:log).permit(:action, :note, :run)
  end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_field :action %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :run %><br>
    <%= f.text_field :run %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<table class="table text-center">
  <thead>
    <tr>
      <th class="text-center">Action</th>
      <th class="text-center">Run</th>
      <th class="text-center">Created</th>
			<th class="text-center">Location</th>
			<th class="text-center">Email</th>
			<th class="text-center">Note</th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.action %></td>
        <td><%= log.run %></td>
        <td><%= log.created_at %></td>
				<td><%= log.location %></td>
				<td><%= log.email %></td>
				<td><%= log.note %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @log.action %>
</p>

<p>
  <strong>Note:</strong>
  <%= @log.note %>
</p>

<p>
  <strong>Run:</strong>
  <%= @log.run %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>